version: "3"
services:
 goapp:
    container_name: goapp
    #build:
    #  dockerfile: ./build/Dockerfile
    image: shomaigu/zissyu:latest
    ports:
      - 8080:8080
#    volumes:
#      - ./cmd/hello:/go/src/app
    restart: always
    tty: true
    command: >
      sh -c 'sleep 30 & go run main.go' 

 db:
    restart: always
    image: shomaigu/zissyu_db:latest
#    build:
#      context: ./
#      dockerfile: ./db/Dockerfile
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: tmcit
      MARIADB_DATABASE: tmcit_quiz_database
      MARIADB_USER: tmcit
      MARIADB_PASSWORD: tmcit
      TZ: 'Asia/Tokyo'
    #volumes:
    #  - ./db/data:/var/lib/mysql
     #  - ./db/my.cnf:/etc/mysql/my.cnf
     # - ./initdb.d/:/docker-entrypoint-initdb.d
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci    
    ports:
      - 3306:3306
