version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    working_dir: /app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tmcit
      MYSQL_DATABASE: tmcit_quiz_database
      MYSQL_USER: tmcit
      MYSQL_PASSWORD: tmcit
      TZ: 'Asia/Tokyo'
      #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d
        #- db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local
