apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goapp
  name: goapp
  namespace: kobayakawake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - image: shomaigu/zissyu:latest
        name: zissyu
        command: ["/bin/sh","-c"]
        args: ["go run main.go"]
        ports:
        - containerPort: 8080