apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: goapp
  name: goapp
  namespace: kobayakawake
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goapp
  type: NodePort
status:

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: kobayakawake
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: NodePort
status: