apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: kobayakawake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: ubuntu:18.04
        tty: true
        name: ubuntu
        command: ["/bin/sh","-c"]
        args: ["apt-get -y update && apt-get -y install iputils-ping net-tools dnsutils && ping db"]